<a href="https://colab.research.google.com/github/arifnayan2861/DA/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [6]:
print(type(arr))
print(arr.shape)

<class 'numpy.ndarray'>
(5,)


In [11]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1, 5)

array([[1, 2, 3, 4, 5]])

In [18]:
arr3 = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(arr3.shape)
print(arr3)

(4, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [10]:
np.arange(0, 10, 3).reshape(4, 1)

array([[0],
       [3],
       [6],
       [9]])

In [12]:
arr = np.array([[1,2,3], [4,5,6]])
print("array shape: ", arr.shape)
print("number of dimensions: ", arr.ndim)
print("number of elements: ", arr.size)
print("data type: ", arr.dtype)
print("size in byte: ", arr.itemsize)

array shape:  (2, 3)
number of dimensions:  2
number of elements:  6
data type:  int64
size in byte:  8


# array slicing and indexing

In [2]:
a = np.array([[1,2,3,4], [5,6,7,8], [9, 10, 11, 12]])
print("array:\n", a)

array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
a[0][0]

1

In [18]:
a[1:][:2]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
a[1:, 2:]

array([[ 7,  8],
       [11, 12]])

In [27]:
a[0:, 1:][:2]

array([[2, 3, 4],
       [6, 7, 8]])

In [47]:
a[0:2, 2:]

array([[3, 4],
       [7, 8]])

In [46]:
a[0:2, 2:]

array([[3, 4],
       [7, 8]])

In [49]:
a[1][2:]

array([7, 8])

In [7]:
a[1:, 1:3]

array([[ 6,  7],
       [10, 11]])

In [8]:
a[1:, :2]

array([[ 5,  6],
       [ 9, 10]])

In [10]:
b = np.array([[1,2,3], [4,5,6]])
b[1:] = 200
b

array([[  1,   2,   3],
       [200, 200, 200]])

In [16]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
mean = data.mean()
median = np.median(data)
std = np.std(data)
variance = np.var(data)
print("mean: ", mean)
print("median: ", median)
print("standard deviation: ", std)
print("variance: ", variance)

mean:  5.5
median:  5.5
standard deviation:  2.8722813232690143
variance:  8.25


In [17]:
data > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [22]:
data[data > 5]

array([ 6,  7,  8,  9, 10])

In [21]:
data[(data > 5) & (data < 8)]

array([6, 7])

In [24]:
data[(data > 5) | (data < 8)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])